compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

supportedArchitectures:
  cpu:
    - x64
    - arm
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.10.3.cjs
