compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.4.1.cjs

supportedArchitectures:
  cpu:
    - x64
    - arm
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux
    - win32
