#set default flavor when missing
{{ if not ( hasKey .Values "flavor" ) }}
{{ $_ := set .Values "flavor" "mainnet" }}
{{ end }}

# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" (list
`nimbus`
`proxyd`
) }}
{{ end }}

#set default number of deployments when missing
{{ if not ( hasKey .Values  "scaling" ) }}
{{ $_ := set .Values "scaling" dict }}
{{ end }}
{{ if not ( hasKey ( .Values | get "scaling" dict ) "deployments" ) }}
{{ $_ := set .Values.scaling "deployments" 1 }}
{{ end }}

environments:
  {{ .Environment.Name }}:
    values:
      - flavor: {{ .Values.flavor }}
      - features: {{ .Values.features | toYaml | nindent 10 }}
      - scaling:
          deployments: {{ .Values.scaling.deployments }}

---
{{- $_tplTransforms := (print `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
{{- $_labels := merge ( .Values | get .release dict | get "resourceLabels" dict ) ( .Values | get "labels" dict ) ( .commonLabels ) }}
{{- $_annotations := merge ( .Values | get .release dict | get "annotations" dict ) ( .Values | get "annotations" dict ) }}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
{{- $_annotations | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
{{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
{{- $_labels | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
{{- end }}
`) -}}
{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := ( print "eth-" .Values.flavor ) }}

commonLabels:
  launchpad.graphops.xyz/namespace: ethereum

{{ $_commonLabels := dict 
  `launchpad.graphops.xyz/namespace` `ethereum`
}}
repositories:
  - name: graphops
    url: https://graphops.github.io/launchpad-charts/canary
  
templates:
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
  
  erigon:
    {{- if ( .Values | get "erigon" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "erigon" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/erigon"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "erigon" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "erigon" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "erigon" dict | get "chartVersion" false ) ( .Values | get "erigon" dict | get "chartUrl" false ) )) }}
    version: "0.8.2"
    {{- end }}
  nimbus:
    {{- if ( .Values | get "nimbus" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "nimbus" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/nimbus"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "nimbus" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "nimbus" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "nimbus" dict | get "chartVersion" false ) ( .Values | get "nimbus" dict | get "chartUrl" false ) )) }}
    version: "0.5.2"
    {{- end }}
  proxyd:
    {{- if ( .Values | get "proxyd" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "proxyd" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/proxyd"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "proxyd" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "proxyd" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "proxyd" dict | get "chartVersion" false ) ( .Values | get "proxyd" dict | get "chartUrl" false ) )) }}
    version: "0.3.4-canary.4"
    {{- end }}
releases:
  {{- $canonicalRelease := "erigon" }}
  {{- range $index := until .Values.scaling.deployments }}
  {{- $deploymentIndex := (add . 1) }}
  {{- $release := (printf "%s%v" "erigon-" $deploymentIndex) }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    {{- tpl $_tplTransforms (dict "Values" .Values "release" $release "commonLabels" $_commonLabels )  | indent 4 -}}
    {{- if ( .Values | get $release dict | get "labels" false ) }}
    labels:
      database.launchpad.graphops.xyz/chain: ethereum
      database.launchpad.graphops.xyz/network: '{{ .Values.flavor }}'
      database.launchpad.graphops.xyz/layer: execution
      
    {{- range $key,$value := ( .Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  {{- end -}}
  {{ if has "nimbus" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "nimbus" }}
  {{- range $index := until .Values.scaling.deployments }}
  {{- $deploymentIndex := (add . 1) }}
  {{- $release := (printf "%s%v" "nimbus-" $deploymentIndex) }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    {{- tpl $_tplTransforms (dict "Values" .Values "release" $release "commonLabels" $_commonLabels )  | indent 4 -}}
    {{- if ( .Values | get $release dict | get "labels" false ) }}
    labels:
      database.launchpad.graphops.xyz/chain: ethereum
      database.launchpad.graphops.xyz/layer: consensus
      
    {{- range $key,$value := ( .Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  {{- end -}}
  {{- end -}}
  {{ if has "proxyd" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "proxyd" }}
  {{- $release := "proxyd" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    {{- tpl $_tplTransforms (dict "Values" .Values "release" $release "commonLabels" $_commonLabels )  | indent 4 -}}
    {{- if ( .Values | get $release dict | get "labels" false ) }}
    labels:
      database.launchpad.graphops.xyz/chain: ethereum
      database.launchpad.graphops.xyz/layer: proxy
      
    {{- range $key,$value := ( .Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
