
bases:
  - ../_common/inheritHelmDefaults.yaml.gotmpl

#set default flavor when missing
{{ if not ( hasKey .Values "flavor" ) }}
{{ $_ := set .Values "flavor" "mainnet" }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := ( print "eth-" .Values.flavor ) }}

commonLabels:
  launchpad.graphops.xyz/namespace: {{ $_defaultNamespace }}

# Repositories for Charts used for Releases in this namespace
repositories:
  - name: graphops
    url: https://graphops.github.io/launchpad-charts

# Import common YAML template definitions
{{ $_tplDefaults := tpl (readFile "../_common/tplDefaults.yaml") dict -}}

{{ $_labels := dict
  "launchpad.graphops.xyz/namespace" $_defaultNamespace
}}

#  "launchpad.graphops.xyz/targetNamespace" .Release.Namespace
#
{{ $_tplTransforms :=
  tpl (readFile "../_common/tplTransforms.yaml.gotmpl") (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    )
-}}

templates:
  transforms:
    {{- $_tplTransforms | nindent 4 }}

  defaults:
    {{- $_tplDefaults | nindent 4 -}}
    namespace: {{ .Values | get "targetNamespace" $_defaultNamespace }}
    inherit:
      - template: transforms

  erigon:
    chart: graphops/erigon
    version: 0.6.0
    inherit:
      - template: defaults

  nimbus:
    chart: graphops/nimbus
    version: 0.3.0
    inherit:
      - template: defaults

  proxyd:
    chart: graphops/proxyd
    version: 0.1.8
    inherit:
      - template: defaults

releases:
    {{- $release := "erigon" }}
  - name: {{ $release }}
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}

    {{- $release := "nimbus" }}
  - name: {{ $release }}
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}

    {{- $release := "proxyd" }}
  - name: {{ $release }}
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}
