#namespace defaults
{{ $_ := set .Values "_namespaceDefaults" ( `{"common":{"targetNamespace":"monitoring","features":["metrics","logs"]}}` | fromJson ) }}

environments:
  {{ .Environment.Name }}:
    values:
      - _namespaceDefaults: {{ .Values._namespaceDefaults | toYaml | nindent 10 }}

---
environments:
  {{ .Environment.Name }}:
    values:
      - _defaults: {{ .Values._namespaceDefaults.common | toYaml | nindent 10 }}

---
# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" .Values._defaults.features }}
{{ end }}


environments:
  {{ .Environment.Name }}:
    values:
      - features: {{ .Values.features | toYaml | nindent 10 }}

---
{{- $_tplTransforms := (print `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
{{- $_labels := .resourceLabels }}
{{- $_annotations := merge ( .Values | get .release dict | get "annotations" dict ) ( .Values | get .canonicalRelease dict | get "annotations" dict ) ( .Values | get "annotations" dict ) }}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
{{- $_annotations | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
{{- end }}
  - path: spec/volumeClaimTemplates[]/metadata/annotations
    kind: StatefulSet
    create: true
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
{{- $_labels | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
{{- end }}
  - path: spec/volumeClaimTemplates[]/metadata/labels
    kind: StatefulSet
    create: true
`) -}}
{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := .Values._defaults.targetNamespace }}


{{- $_commonLabels := dict 
`launchpad.graphops.xyz/namespace` `monitoring`
`launchpad.graphops.xyz/layer` `base`
}}

{{- $_commonResourceLabels := dict 

}}
{{ $_ := mergeOverwrite $_commonResourceLabels $_commonLabels }}
{{- if hasKey .Values "labels" }}
{{- range $key, $value := $.Values.labels }}
{{- $_ := set $_commonLabels $key $value }}
{{- $_ := set $_commonResourceLabels $key $value }}
{{- end }}
{{- end }}
{{- if hasKey .Values "resourceLabels" }}
{{- range $key, $value := $.Values.resourceLabels }}
{{- $_ := set $_commonResourceLabels $key $value }}
{{- end }}
{{- end }}
commonLabels:
{{- range $key, $value := $_commonLabels }}
  {{ $key }}: {{ $value }}
{{- end }}
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: deliveryhero
    url: https://charts.deliveryhero.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  
templates:
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
  
  kube-prometheus-stack:
    {{- if ( .Values | get "kube-prometheus-stack" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "kube-prometheus-stack" | get "chartUrl" }}
    {{- else }}
    chart: "prometheus-community/kube-prometheus-stack"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "kube-prometheus-stack" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "kube-prometheus-stack" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "kube-prometheus-stack" dict | get "chartVersion" false ) ( .Values | get "kube-prometheus-stack" dict | get "chartUrl" false ) )) }}
    version: "57.1.1"
    {{- end }}
    disableValidationOnInstall: true
  
  node-problem-detector:
    {{- if ( .Values | get "node-problem-detector" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "node-problem-detector" | get "chartUrl" }}
    {{- else }}
    chart: "deliveryhero/node-problem-detector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "node-problem-detector" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "node-problem-detector" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "node-problem-detector" dict | get "chartVersion" false ) ( .Values | get "node-problem-detector" dict | get "chartUrl" false ) )) }}
    version: "2.3.12"
    {{- end }}
  
  loki:
    {{- if ( .Values | get "loki" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "loki" | get "chartUrl" }}
    {{- else }}
    chart: "grafana/loki-distributed"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "loki" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "loki" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "loki" dict | get "chartVersion" false ) ( .Values | get "loki" dict | get "chartUrl" false ) )) }}
    version: "0.78.3"
    {{- end }}
  
  promtail:
    {{- if ( .Values | get "promtail" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "promtail" | get "chartUrl" }}
    {{- else }}
    chart: "grafana/promtail"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "promtail" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "promtail" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "promtail" dict | get "chartVersion" false ) ( .Values | get "promtail" dict | get "chartUrl" false ) )) }}
    version: "6.15.5"
    {{- end }}
  
releases:
  {{ if has "metrics" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "kube-prometheus-stack" }}
  {{- $release := "kube-prometheus-stack" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "metrics" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "node-problem-detector" }}
  {{- $release := "node-problem-detector" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "logs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "loki" }}
  {{- $release := "loki" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "logs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "promtail" }}
  {{- $release := "promtail" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
