{{- $_tplTransforms := `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
  {{- . | get "annotations" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
  {{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
  {{- . | get "labels" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
  {{- end }}
` -}}

{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{` "`{{ .Release.Name }}`" `}}.yaml
- ./values/{{ .Values.flavor }}/{{` "`{{ .Release.Name }}`" `}}.yaml
{{- else }}
- ./values/{{` "`{{ .Release.Name }}`" `}}.yaml
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}

{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}


# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" (list
`metrics`
`logs`
) }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := `monitoring` }}

commonLabels:
  launchpad.graphops.xyz/namespace: monitoring
  launchpad.graphops.xyz/layer: base

{{ $_labels := dict 
  `launchpad.graphops.xyz/namespace` `monitoring`
  `launchpad.graphops.xyz/layer` `base`
}}
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: deliveryhero
    url: https://charts.deliveryhero.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  
templates:
  transforms:
    {{ tpl $_tplTransforms (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    ) | nindent 4 }}
  
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
    inherit:
      - template: transforms
  
  kube-prometheus-stack:
    chart: prometheus-community/kube-prometheus-stack
    version: 51.0.2
    inherit:
      - template: defaults
    disableValidationOnInstall: true
  
  node-problem-detector:
    chart: deliveryhero/node-problem-detector
    version: 2.3.10
    inherit:
      - template: defaults
  
  loki:
    chart: grafana/loki-distributed
    version: 0.74.1
    inherit:
      - template: defaults
  
  promtail:
    chart: grafana/promtail
    version: 6.15.1
    inherit:
      - template: defaults
  
releases:
  {{ if has "metrics" ( .Values | get "features" list ) }}
  {{- $release := "kube-prometheus-stack" }}
  - name: 'kube-prometheus-stack'
    inherit:
    - template: 'kube-prometheus-stack'
    values:
    {{- tpl $_tplReleaseValues (dict "Values" .Values "release" $release)  | indent 4 -}}
  {{- end -}}
  {{ if has "metrics" ( .Values | get "features" list ) }}
  {{- $release := "node-problem-detector" }}
  - name: 'node-problem-detector'
    inherit:
    - template: 'node-problem-detector'
    values:
    {{- tpl $_tplReleaseValues (dict "Values" .Values "release" $release)  | indent 4 -}}
  {{- end -}}
  {{ if has "logs" ( .Values | get "features" list ) }}
  {{- $release := "loki" }}
  - name: 'loki'
    inherit:
    - template: 'loki'
    values:
    {{- tpl $_tplReleaseValues (dict "Values" .Values "release" $release)  | indent 4 -}}
  {{- end -}}
  {{ if has "logs" ( .Values | get "features" list ) }}
  {{- $release := "promtail" }}
  - name: 'promtail'
    inherit:
    - template: 'promtail'
    values:
    {{- tpl $_tplReleaseValues (dict "Values" .Values "release" $release)  | indent 4 -}}
  {{- end -}}
