
# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" (list
`metrics`
`logs`
) }}
{{ end }}


environments:
  {{ .Environment.Name }}:
    values:
      - features: {{ .Values.features | toYaml | nindent 10 }}

---
{{- $_tplTransforms := `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
  {{- . | get "annotations" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
  {{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
  {{- . | get "labels" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
  {{- end }}
` -}}

{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := `monitoring` }}

commonLabels:
  launchpad.graphops.xyz/namespace: monitoring
  launchpad.graphops.xyz/layer: base

{{ $_labels := dict 
  `launchpad.graphops.xyz/namespace` `monitoring`
  `launchpad.graphops.xyz/layer` `base`
}}
repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: deliveryhero
    url: https://charts.deliveryhero.io
  - name: grafana
    url: https://grafana.github.io/helm-charts
  
templates:
  transforms:
    {{ tpl $_tplTransforms (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    ) | nindent 4 }}
  
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
    inherit:
      - template: transforms
  
  kube-prometheus-stack:
    {{- if ( .Values | get "kube-prometheus-stack" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "kube-prometheus-stack" | get "chartUrl" }}
    {{- else }}
    chart: "prometheus-community/kube-prometheus-stack"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "kube-prometheus-stack" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "kube-prometheus-stack" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "kube-prometheus-stack" dict | get "chartVersion" false ) ( .Values | get "kube-prometheus-stack" dict | get "chartUrl" false ) )) }}
    version: "51.0.2"
    {{- end }}
  node-problem-detector:
    {{- if ( .Values | get "node-problem-detector" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "node-problem-detector" | get "chartUrl" }}
    {{- else }}
    chart: "deliveryhero/node-problem-detector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "node-problem-detector" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "node-problem-detector" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "node-problem-detector" dict | get "chartVersion" false ) ( .Values | get "node-problem-detector" dict | get "chartUrl" false ) )) }}
    version: "2.3.10"
    {{- end }}
  loki:
    {{- if ( .Values | get "loki" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "loki" | get "chartUrl" }}
    {{- else }}
    chart: "grafana/loki-distributed"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "loki" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "loki" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "loki" dict | get "chartVersion" false ) ( .Values | get "loki" dict | get "chartUrl" false ) )) }}
    version: "0.74.1"
    {{- end }}
  promtail:
    {{- if ( .Values | get "promtail" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "promtail" | get "chartUrl" }}
    {{- else }}
    chart: "grafana/promtail"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "promtail" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "promtail" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "promtail" dict | get "chartVersion" false ) ( .Values | get "promtail" dict | get "chartUrl" false ) )) }}
    version: "6.15.1"
    {{- end }}
releases:
  {{ if has "metrics" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "kube-prometheus-stack" }}
  {{- $release := "kube-prometheus-stack" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "metrics" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "node-problem-detector" }}
  {{- $release := "node-problem-detector" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "logs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "loki" }}
  {{- $release := "loki" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "logs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "promtail" }}
  {{- $release := "promtail" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
