
bases:
  - ../_common/inheritHelmDefaults.yaml.gotmpl


#set default namespace
{{ $_defaultNamespace := "sealed-secrets" }}

commonLabels:
  launchpad.graphops.xyz/namespace: {{ $_defaultNamespace }}
  launchpad.graphops.xyz/layer: "base"

# Repositories for Charts used for Releases in this namespace
repositories:
  - name: sealed-secrets
    url: https://bitnami-labs.github.io/sealed-secrets

# Import common YAML template definitions
{{ $_tplDefaults := tpl (readFile "../_common/tplDefaults.yaml") dict -}}

{{ $_labels := dict
  "launchpad.graphops.xyz/namespace" $_defaultNamespace
}}

#  "launchpad.graphops.xyz/targetNamespace" .Release.Namespace
#
{{ $_tplTransforms :=
  tpl (readFile "../_common/tplTransforms.yaml.gotmpl") (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    )
-}}

templates:
  transforms:
    {{- $_tplTransforms | nindent 4 }}

  defaults:
    {{- $_tplDefaults | nindent 4 -}}
    namespace: {{ .Values | get "targetNamespace" $_defaultNamespace }}
    inherit:
      - template: transforms

  sealed-secrets:
    chart: sealed-secrets/sealed-secrets
    version: 2.6.9
    inherit:
      - template: defaults

releases:
    {{- $release := "sealed-secrets" }}
  - name: {{ $release }}
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}
