#namespace defaults
{{ $_ := set .Values "_defaults" ( `{"common":{"targetNamespace":"storage","features":["rawfile"]}}` | fromJson ) }}

environments:
  {{ .Environment.Name }}:
    values:
      - _defaults: {{ .Values._defaults | toYaml | nindent 10 }}

---
# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" .Values._defaults.common.features }}
{{ end }}


environments:
  {{ .Environment.Name }}:
    values:
      - _defaults: {{ .Values._defaults | toYaml | nindent 10 }}
      - features: {{ .Values.features | toYaml | nindent 10 }}

---
{{- $_tplTransforms := (print `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
{{- $_labels := .resourceLabels }}
{{- $_annotations := merge ( .Values | get .release dict | get "annotations" dict ) ( .Values | get .canonicalRelease dict | get "annotations" dict ) ( .Values | get "annotations" dict ) }}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
{{- $_annotations | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
{{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
{{- $_labels | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
{{- end }}
`) -}}
{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := .Values._defaults.common.targetNamespace }}


{{- $_commonLabels := dict 
`launchpad.graphops.xyz/namespace` `storage`
`launchpad.graphops.xyz/layer` `base`
}}

{{- $_commonResourceLabels := dict 

}}
{{ $_ := mergeOverwrite $_commonResourceLabels $_commonLabels }}
{{- if hasKey .Values "labels" }}
{{- range $key, $value := $.Values.labels }}
{{- $_ := set $_commonLabels $key $value }}
{{- $_ := set $_commonResourceLabels $key $value }}
{{- end }}
{{- end }}
{{- if hasKey .Values "resourceLabels" }}
{{- range $key, $value := $.Values.resourceLabels }}
{{- $_ := set $_commonResourceLabels $key $value }}
{{- end }}
{{- end }}
commonLabels:
{{- range $key, $value := $_commonLabels }}
  {{ $key }}: {{ $value }}
{{- end }}
repositories:
  - name: openebs
    url: https://openebs.github.io/charts
  - name: graphops
    url: https://graphops.github.io/launchpad-charts/canary
  - name: openebs-zfs-localpv
    url: https://openebs.github.io/zfs-localpv
  
templates:
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
  
  openebs:
    {{- if ( .Values | get "openebs" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "openebs" | get "chartUrl" }}
    {{- else }}
    chart: "openebs/openebs"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "openebs" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "openebs" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "openebs" dict | get "chartVersion" false ) ( .Values | get "openebs" dict | get "chartUrl" false ) )) }}
    version: "3.9.0"
    {{- end }}
  openebs-rawfile-localpv:
    {{- if ( .Values | get "openebs-rawfile-localpv" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "openebs-rawfile-localpv" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/openebs-rawfile-localpv"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "openebs-rawfile-localpv" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "openebs-rawfile-localpv" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "openebs-rawfile-localpv" dict | get "chartVersion" false ) ( .Values | get "openebs-rawfile-localpv" dict | get "chartUrl" false ) )) }}
    version: "0.8.3"
    {{- end }}
  openebs-rawfile-storageclass:
    {{- if ( .Values | get "openebs-rawfile-storageclass" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "openebs-rawfile-storageclass" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/resource-injector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "openebs-rawfile-storageclass" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "openebs-rawfile-storageclass" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "openebs-rawfile-storageclass" dict | get "chartVersion" false ) ( .Values | get "openebs-rawfile-storageclass" dict | get "chartUrl" false ) )) }}
    version: "0.2.0"
    {{- end }}
  openebs-zfs-localpv:
    {{- if ( .Values | get "openebs-zfs-localpv" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "openebs-zfs-localpv" | get "chartUrl" }}
    {{- else }}
    chart: "openebs-zfs-localpv/zfs-localpv"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "openebs-zfs-localpv" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "openebs-zfs-localpv" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "openebs-zfs-localpv" dict | get "chartVersion" false ) ( .Values | get "openebs-zfs-localpv" dict | get "chartUrl" false ) )) }}
    version: "2.3.1"
    {{- end }}
  openebs-zfs-storageclass:
    {{- if ( .Values | get "openebs-zfs-storageclass" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "openebs-zfs-storageclass" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/resource-injector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "openebs-zfs-storageclass" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "openebs-zfs-storageclass" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "openebs-zfs-storageclass" dict | get "chartVersion" false ) ( .Values | get "openebs-zfs-storageclass" dict | get "chartUrl" false ) )) }}
    version: "0.2.0"
    {{- end }}
  openebs-zfs-snapclass:
    {{- if ( .Values | get "openebs-zfs-snapclass" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "openebs-zfs-snapclass" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/resource-injector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "openebs-zfs-snapclass" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "openebs-zfs-snapclass" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "openebs-zfs-snapclass" dict | get "chartVersion" false ) ( .Values | get "openebs-zfs-snapclass" dict | get "chartUrl" false ) )) }}
    version: "0.2.0"
    {{- end }}
releases:
  {{- $canonicalRelease := "openebs" }}
  {{- $release := "openebs" }}
    {{- $_releaseResourceLabels := deepCopy $_commonResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{ if has "rawfile" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "openebs-rawfile-localpv" }}
  {{- $release := "openebs-rawfile-localpv" }}
    {{- $_releaseResourceLabels := deepCopy $_commonResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "rawfile" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "openebs-rawfile-storageclass" }}
  {{- $release := "openebs-rawfile-storageclass" }}
    {{- $_releaseResourceLabels := deepCopy $_commonResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "zfs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "openebs-zfs-localpv" }}
  {{- $release := "openebs-zfs-localpv" }}
    {{- $_releaseResourceLabels := deepCopy $_commonResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "zfs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "openebs-zfs-storageclass" }}
  {{- $release := "openebs-zfs-storageclass" }}
    {{- $_releaseResourceLabels := deepCopy $_commonResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "zfs" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "openebs-zfs-snapclass" }}
  {{- $release := "openebs-zfs-snapclass" }}
    {{- $_releaseResourceLabels := deepCopy $_commonResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
