
bases:
  - ../_common/inheritHelmDefaults.yaml.gotmpl


#set default namespace
{{ $_defaultNamespace := "storage" }}

commonLabels:
  launchpad.graphops.xyz/namespace: {{ $_defaultNamespace }}
  launchpad.graphops.xyz/layer: "base"


# Repositories for Charts used for Releases in this namespace
repositories:
  - name: openebs
    url: https://openebs.github.io/charts
  - name: openebs-zfs-localpv
    url: https://openebs.github.io/zfs-localpv
  - name: openebs-monitoring
    url: https://openebs.github.io/monitoring/
  - name: graphops
    url: https://graphops.github.io/launchpad-charts

# Import common YAML template definitions
{{ $_tplDefaults := tpl (readFile "../_common/tplDefaults.yaml") dict -}}

{{ $_labels := dict
  "launchpad.graphops.xyz/namespace" $_defaultNamespace
}}

{{ $_tplTransforms :=
  tpl (readFile "../_common/tplTransforms.yaml.gotmpl") (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    )
-}}

templates:
  transforms:
    {{- $_tplTransforms | nindent 4 }}

  defaults:
    {{- $_tplDefaults | nindent 4 -}}
    namespace: {{ .Values | get "targetNamespace" $_defaultNamespace }}
    inherit:
      - template: transforms

  resource-injector:
    chart: graphops/resource-injector
    version: 0.2.0
    inherit:
      - template: defaults

  openebs:
    chart: openebs/openebs
    version: 3.6.0
    inherit:
      - template: defaults

  openebs-rawfile-localpv:
    chart: graphops/openebs-rawfile-localpv
    version: 0.8.0
    inherit:
      - template: defaults

  openebs-zfs-localpv:
    chart: openebs-zfs-localpv/zfs-localpv
    version: 2.1.0
    inherit:
      - template: defaults

  openebs-monitoring:
    chart: openebs-monitoring/openebs-monitoring
    version: 0.4.10
    inherit:
      - template: defaults

# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" (list
  "openebs"
  "rawfile"
) }}
{{ end }}

releases:
  {{- if has "openebs" ( .Values | get "features" list ) }}
    {{- $release := "openebs" }}
  - name: {{ $release }}
    labels:
      feature: "openebs"
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}
  {{- end -}}

  {{ if has "rawfile" ( .Values | get "features" list ) }}
    {{- $release := "openebs-rawfile-localpv" }}
  - name: {{ $release }}
    labels:
      feature: "rawfile"
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}

    {{- $release := "openebs-rawfile-storageclass" }}
  - name: {{ $release }}
    labels:
      feature: "rawfile"
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release "resource-injector" true)  | nindent 4 -}}
  {{- end -}}

  {{ if has "zfs" ( .Values | get "features" list ) }}
    {{- $release := "openebs-zfs-localpv" }}
  - name: {{ $release }}
    labels:
      feature: "zfs"
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release)  | nindent 4 -}}

    {{- $release := "openebs-zfs-storageclass" }}
  - name: {{ $release }}
    labels:
      feature: "zfs"
    {{- tpl (readFile "../_common/tplRelease.yaml.gotmpl") (dict "Values" .Values "release" $release "resource-injector" true)  | nindent 4 -}}
  {{- end -}}
