#set default flavor when missing
{{ if not ( hasKey .Values "flavor" ) }}
{{ $_ := set .Values "flavor" "mainnet" }}
{{ end }}



environments:
  {{ .Environment.Name }}:
    values:
      - flavor: {{ .Values.flavor }}

---
{{- $_tplTransforms := (print `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
{{- $_labels := merge ( .Values | get .release dict | get "resourceLabels" dict ) ( .Values | get "labels" dict ) ( .commonLabels ) }}
{{- $_annotations := merge ( .Values | get .release dict | get "annotations" dict ) ( .Values | get "annotations" dict ) }}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
{{- $_annotations | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
{{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
{{- $_labels | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
{{- end }}
`) -}}
{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := ( print "avalanche-" .Values.flavor ) }}

commonLabels:
  launchpad.graphops.xyz/namespace: avalanche

{{ $_commonLabels := dict 
  `launchpad.graphops.xyz/namespace` `avalanche`
}}
repositories:
  - name: graphops
    url: https://graphops.github.io/launchpad-charts/canary
  
templates:
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
  
  avalanche:
    {{- if ( .Values | get "avalanche" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "avalanche" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/avalanche"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "avalanche" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "avalanche" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "avalanche" dict | get "chartVersion" false ) ( .Values | get "avalanche" dict | get "chartUrl" false ) )) }}
    version: "0.1.0"
    {{- end }}
  proxyd:
    {{- if ( .Values | get "proxyd" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "proxyd" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/proxyd"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "proxyd" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "proxyd" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "proxyd" dict | get "chartVersion" false ) ( .Values | get "proxyd" dict | get "chartUrl" false ) )) }}
    version: "0.1.8"
    {{- end }}
releases:
  {{- $canonicalRelease := "avalanche" }}
  {{- $release := "avalanche" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    {{- tpl $_tplTransforms (dict "Values" .Values "release" $release "commonLabels" $_commonLabels )  | indent 4 -}}
    {{- if ( .Values | get $release dict | get "labels" false ) }}
    labels:
    {{- range $key,$value := ( .Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- $canonicalRelease := "proxyd" }}
  {{- $release := "proxyd" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    {{- tpl $_tplTransforms (dict "Values" .Values "release" $release "commonLabels" $_commonLabels )  | indent 4 -}}
    {{- if ( .Values | get $release dict | get "labels" false ) }}
    labels:
    {{- range $key,$value := ( .Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- end }}
    {{- end }}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
