


environments:
  {{ .Environment.Name }}:
    values: []

---
{{- $_tplTransforms := `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
  {{- . | get "annotations" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
  {{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
  {{- . | get "labels" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
  {{- end }}
` -}}

{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := `postgres-operator` }}

commonLabels:
  launchpad.graphops.xyz/namespace: postgres-operator
  launchpad.graphops.xyz/layer: base

{{ $_labels := dict 
  `launchpad.graphops.xyz/namespace` `postgres-operator`
  `launchpad.graphops.xyz/layer` `base`
}}
repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  
templates:
  transforms:
    {{ tpl $_tplTransforms (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    ) | nindent 4 }}
  
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
    inherit:
      - template: transforms
  
  postgres-operator:
    {{- if ( .Values | get "postgres-operator" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "postgres-operator" | get "chartUrl" }}
    {{- else }}
    chart: "postgres-operator-charts/postgres-operator"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "postgres-operator" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "postgres-operator" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "postgres-operator" dict | get "chartVersion" false ) ( .Values | get "postgres-operator" dict | get "chartUrl" false ) )) }}
    version: "1.10.1"
    {{- end }}
releases:
  {{- $canonicalRelease := "postgres-operator" }}
  {{- $release := "postgres-operator" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
