#set default flavor when missing
{{ if not ( hasKey .Values "flavor" ) }}
{{ $_ := set .Values "flavor" "mainnet" }}
{{ end }}



environments:
  {{ .Environment.Name }}:
    values:
      - flavor: {{ .Values.flavor }}

---
{{- $_tplTransforms := `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
  {{- . | get "annotations" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
  {{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
  {{- . | get "labels" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
  {{- end }}
` -}}

{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := ( print "polygon-" .Values.flavor ) }}

commonLabels:
  launchpad.graphops.xyz/namespace: polygon

{{ $_labels := dict 
  `launchpad.graphops.xyz/namespace` `polygon`
}}
repositories:
  - name: graphops
    url: https://graphops.github.io/launchpad-charts/canary
  
templates:
  transforms:
    {{ tpl $_tplTransforms (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    ) | nindent 4 }}
  
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
    inherit:
      - template: transforms
  
  erigon:
    {{- if ( .Values | get "erigon" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "erigon" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/erigon"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "erigon" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "erigon" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "erigon" dict | get "chartVersion" false ) ( .Values | get "erigon" dict | get "chartUrl" false ) )) }}
    version: "0.6.1-canary.1"
    {{- end }}
  heimdall:
    {{- if ( .Values | get "heimdall" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "heimdall" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/heimdall"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "heimdall" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "heimdall" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "heimdall" dict | get "chartVersion" false ) ( .Values | get "heimdall" dict | get "chartUrl" false ) )) }}
    version: "1.1.1"
    {{- end }}
  proxyd:
    {{- if ( .Values | get "proxyd" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "proxyd" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/proxyd"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "proxyd" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "proxyd" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "proxyd" dict | get "chartVersion" false ) ( .Values | get "proxyd" dict | get "chartUrl" false ) )) }}
    version: "0.2.1"
    {{- end }}
releases:
  {{- $canonicalRelease := "erigon" }}
  {{- $release := "erigon" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- $canonicalRelease := "heimdall" }}
  {{- $release := "heimdall" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- $canonicalRelease := "proxyd" }}
  {{- $release := "proxyd" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
