#namespace defaults
{{ $_ := set .Values "_defaults" ( `{"common":{"targetNamespace":"ingress","features":["ingress","cert-manager"]}}` | fromJson ) }}

environments:
  {{ .Environment.Name }}:
    values:
      - _defaults: {{ .Values._defaults | toYaml | nindent 10 }}

---
# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" .Values._defaults.common.features }}
{{ end }}


environments:
  {{ .Environment.Name }}:
    values:
      - features: {{ .Values.features | toYaml | nindent 10 }}

---
{{- $_tplTransforms := (print `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
{{- $_labels := .resourceLabels }}
{{- $_annotations := merge ( .Values | get .release dict | get "annotations" dict ) ( .Values | get .canonicalRelease dict | get "annotations" dict ) ( .Values | get "annotations" dict ) }}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
{{- $_annotations | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
{{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
{{- $_labels | toYaml | nindent 4 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
{{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
{{- end }}
`) -}}
{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := .Values._defaults.common.targetNamespace }}


{{- $_commonLabels := dict 
`launchpad.graphops.xyz/namespace` `ingress`
`launchpad.graphops.xyz/layer` `base`
}}

{{- $_commonResourceLabels := dict 

}}
{{ $_ := mergeOverwrite $_commonResourceLabels $_commonLabels }}
{{- if hasKey .Values "labels" }}
{{- range $key, $value := $.Values.labels }}
{{- $_ := set $_commonLabels $key $value }}
{{- $_ := set $_commonResourceLabels $key $value }}
{{- end }}
{{- end }}
{{- if hasKey .Values "resourceLabels" }}
{{- range $key, $value := $.Values.resourceLabels }}
{{- $_ := set $_commonResourceLabels $key $value }}
{{- end }}
{{- end }}
commonLabels:
{{- range $key, $value := $_commonLabels }}
  {{ $key }}: {{ $value }}
{{- end }}
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: graphops
    url: https://graphops.github.io/launchpad-charts/canary
  
templates:
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
  
  ingress-nginx:
    {{- if ( .Values | get "ingress-nginx" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "ingress-nginx" | get "chartUrl" }}
    {{- else }}
    chart: "ingress-nginx/ingress-nginx"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "ingress-nginx" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "ingress-nginx" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "ingress-nginx" dict | get "chartVersion" false ) ( .Values | get "ingress-nginx" dict | get "chartUrl" false ) )) }}
    version: "4.9.1"
    {{- end }}
  
  cert-manager:
    {{- if ( .Values | get "cert-manager" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "cert-manager" | get "chartUrl" }}
    {{- else }}
    chart: "jetstack/cert-manager"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "cert-manager" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "cert-manager" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "cert-manager" dict | get "chartVersion" false ) ( .Values | get "cert-manager" dict | get "chartUrl" false ) )) }}
    version: "v1.14.1"
    {{- end }}
    disableValidationOnInstall: true
  
  cert-manager-resources:
    {{- if ( .Values | get "cert-manager-resources" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "cert-manager-resources" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/resource-injector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "cert-manager-resources" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "cert-manager-resources" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "cert-manager-resources" dict | get "chartVersion" false ) ( .Values | get "cert-manager-resources" dict | get "chartUrl" false ) )) }}
    version: "0.2.0"
    {{- end }}
  
releases:
  {{ if has "ingress" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "ingress-nginx" }}
  {{- $release := "ingress-nginx" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "cert-manager" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "cert-manager" }}
  {{- $release := "cert-manager" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "cert-manager" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "cert-manager-resources" }}
  {{- $release := "cert-manager-resources" }}
  {{- $_releaseResourceLabels := dict }}
  {{- $_releaseResourceLabels = mergeOverwrite $_commonLabels $_commonResourceLabels $_releaseResourceLabels }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    labels:
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "labels" dict ) }}
      {{ $key }}: {{ $value }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- range $key,$value := ( $.Values | get $canonicalRelease dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- if (ne $release $canonicalRelease) }}
    {{- range $key,$value := ( $.Values | get $release dict | get "resourceLabels" dict ) }}
    {{- $_ := set $_releaseResourceLabels $key $value }}
    {{- end }}
    {{- end }}
    {{- tpl $_tplTransforms (dict "Values" $.Values "release" $release "canonicalRelease" $canonicalRelease "resourceLabels" $_releaseResourceLabels  )  | indent 4 -}}
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
