
# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" (list
`ingress`
`cert-manager`
) }}
{{ end }}


environments:
  default:
    values:
    - features: {{ .Values.features | toYaml | nindent 10 }}
---
{{- $_tplTransforms := `
{{- $_TemplatedResources := list "Deployment" "StatefulSet" "DaemonSet" -}}
transformers:
- apiVersion: builtin
  kind: AnnotationsTransformer
  metadata:
    name: AddAnnotations
  annotations:
  {{- . | get "annotations" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/annotations
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/annotations
    create: true
  {{- end }}
- apiVersion: builtin
  kind: LabelTransformer
  metadata:
    name: AddLabels
  labels:
  {{- . | get "labels" dict | toYaml | nindent 6 }}
  fieldSpecs:
  - path: metadata/labels
    create: true
  {{- range $kind := $_TemplatedResources }}
  - kind: {{ $kind }}
    path: spec/template/metadata/labels
    create: true
  {{- end }}
` -}}

{{- $_tplReleaseValues := (print `
{{- if ( .Values | get .release dict | get "mergeValues" true ) -}}
{{- if ( hasKey .Values "flavor" ) }}
- ./values/_common/{{ .canonicalRelease }}.yaml
- ./values/_common/{{ .canonicalRelease }}.yaml.gotmpl
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml
- ./values/{{ .Values.flavor }}/{{ .canonicalRelease }}.yaml.gotmpl
{{- else }}
- ./values/{{ .canonicalRelease }}.yaml
- ./values/{{ .canonicalRelease }}.yaml.gotmpl
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .canonicalRelease dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .canonicalRelease dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .canonicalRelease dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
{{- end -}}
{{- if typeIs ( typeOf list ) ( .Values | get .release dict | get "values" dict ) -}}
 {{- range $element := ( .Values | get .release dict | get "values" dict ) }}
- {{- $element | toYaml | nindent 2 }}
 {{- end -}}
{{- else }}
- {{- .Values | get .release dict | get "values" dict | toYaml | nindent 2 }}
{{- end -}}
`) -}}
{{ $__helmDefaults := `{"recreatePods":true}` | fromJson }}

{{ with ( .Values | get "helmDefaults" dict ) }}
{{ $_ := (deepCopy . | mergeOverwrite $__helmDefaults) }}
{{ end }}

helmDefaults:
{{ $__helmDefaults | toYaml | indent 2 }}

{{ if ( hasKey .Values "kubeVersion" ) }}
kubeVersion: {{ .Values.kubeVersion }}
{{ end }}

#set default namespace
{{ $_defaultNamespace := `ingress` }}

commonLabels:
  launchpad.graphops.xyz/namespace: ingress
  launchpad.graphops.xyz/layer: base

{{ $_labels := dict 
  `launchpad.graphops.xyz/namespace` `ingress`
  `launchpad.graphops.xyz/layer` `base`
}}
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: jetstack
    url: https://charts.jetstack.io
  - name: graphops
    url: https://graphops.github.io/launchpad-charts/canary
  
templates:
  transforms:
    {{ tpl $_tplTransforms (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    ) | nindent 4 }}
  
  defaults:
    namespace: '{{ .Values | get "targetNamespace" $_defaultNamespace }}'
    missingFileHandler: Warn
    inherit:
      - template: transforms
  
  ingress-nginx:
    {{- if ( .Values | get "ingress-nginx" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "ingress-nginx" | get "chartUrl" }}
    {{- else }}
    chart: "ingress-nginx/ingress-nginx"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "ingress-nginx" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "ingress-nginx" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "ingress-nginx" dict | get "chartVersion" false ) ( .Values | get "ingress-nginx" dict | get "chartUrl" false ) )) }}
    version: "4.7.2"
    {{- end }}
  cert-manager:
    {{- if ( .Values | get "cert-manager" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "cert-manager" | get "chartUrl" }}
    {{- else }}
    chart: "jetstack/cert-manager"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "cert-manager" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "cert-manager" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "cert-manager" dict | get "chartVersion" false ) ( .Values | get "cert-manager" dict | get "chartUrl" false ) )) }}
    version: "v1.13.0"
    {{- end }}
  cert-manager-resources:
    {{- if ( .Values | get "cert-manager-resources" dict | get "chartUrl" false ) }}
    chart: {{ .Values | get "cert-manager-resources" | get "chartUrl" }}
    {{- else }}
    chart: "graphops/resource-injector"
    {{- end }}
    inherit:
    - template: "defaults"
    {{- if ( .Values | get "cert-manager-resources" dict | get "chartVersion" false ) }}
    version: {{ .Values | get "cert-manager-resources" | get "chartVersion" }}
    {{- end }}
    {{- if (not (or ( .Values | get "cert-manager-resources" dict | get "chartVersion" false ) ( .Values | get "cert-manager-resources" dict | get "chartUrl" false ) )) }}
    version: "0.2.0"
    {{- end }}
releases:
  {{ if has "ingress" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "ingress-nginx" }}
  {{- $release := "ingress-nginx" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "cert-manager" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "cert-manager" }}
  {{- $release := "cert-manager" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
  {{ if has "cert-manager" ( .Values | get "features" list ) }}
  {{- $canonicalRelease := "cert-manager-resources" }}
  {{- $release := "cert-manager-resources" }}
  - name: "{{ $release }}"
    inherit:
    - template: "{{ $canonicalRelease }}"
    values:
    {{- tpl $_tplReleaseValues (dict "Values" $.Values "canonicalRelease" $canonicalRelease "release" $release) | indent 4 -}}
  
  {{- end -}}
