
bases:
  - ../_common/inheritHelmDefaults.yaml.gotmpl

#set default namespace
{{ $_defaultNamespace := "ingress" }}

commonLabels:
  namespace: {{ $_defaultNamespace }}

# Repositories for Charts used for Releases in this namespace
repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: vouch
    url: https://vouch.github.io/helm-charts/
  - name: jetstack
    url: https://charts.jetstack.io

# Import common YAML template definitions
{{ $_tplDefaults := tpl (readFile "../_common/tplDefaults.yaml") dict -}}

{{ $_labels := dict
  "launchpad.graphops.xyz/namespace" $_defaultNamespace
}}

{{ $_tplTransforms :=
  tpl (readFile "../_common/tplTransforms.yaml.gotmpl") (dict
    "annotations" ( .Values | get "annotations" dict)
    "labels" ( merge $_labels ( .Values | get "labels" dict) )
    )
-}}

# Anchors for each default release definition, their default values, and any inner resources that are relevant
templates:
  transforms:
    {{- $_tplTransforms | nindent 4 }}

  defaults:
    {{- $_tplDefaults | nindent 4 -}}
    namespace: {{ .Values | get "targetNamespace" $_defaultNamespace }}
    inherit:
      - template: transforms

  resource-injector:
    chart: graphops/resource-injector
    version: 0.2.0
    inherit:
      - template: defaults

  ingress-nginx:
    chart: ingress-nginx/ingress-nginx
    version: 4.3.0
    inherit:
      - template: defaults

  cert-manager:
    chart: jetstack/cert-manager
    version: v1.10.0
    inherit:
      - template: defaults
    disableValidationOnInstall: true # For CRDs https://github.com/helmfile/helmfile/blob/main/pkg/state/state.go#L236
    wait: true

# Define default features when undefined
{{ if not (hasKey .Values "features") }}
{{ $_ := set .Values "features" (list
  "ingress"
  "cert-manager"
) }}
{{ end }}

releases:
  {{ if has "ingress" ( .Values | get "features" list ) }}
    {{ $release := "ingress-nginx" }}
  - name: {{ $release }}
    inherit:
      - template: {{ $release }}
    labels:
      feature: "ingress"
    values:
      - ./values/{{`{{ .Release.Name }}`}}.yaml
      - {{ .Values | get $release dict | get "values" dict | toYaml }}
  {{ end }}

  {{ if has "cert-manager" ( .Values | get "features" list ) }}
    {{ $release := "cert-manager" }}
  - name: {{ $release }}
    inherit:
      - template: {{ $release }}
    labels:
      feature: "cert-manager"
    values:
      - ./values/{{`{{ .Release.Name }}`}}.yaml
      - {{ .Values | get $release dict | get "values" dict | toYaml }}

  - name: cert-manager-resources
    inherit:
      - template: resource-injector
    labels:
      feature: "cert-manager"
    values:
      - ./values/{{`{{ .Release.Name }}`}}.yaml
      - {{ .Values | get $release dict | get "values" dict | toYaml }}
    disableValidationOnInstall: true # For CRDs https://github.com/helmfile/helmfile/blob/main/pkg/state/state.go#L236
  {{ end }}
