defaultRules:
  rules:
    # disabling for embedded k0s processes https://github.com/k0sproject/k0s/issues/611#issuecomment-756655575
    kubeControllerManager: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false

prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-rawfile-localpv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: openebs-rawfile-localpv
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  deploymentStrategy:
    type: Recreate
  enabled: true
  persistence:
    enabled: true
    type: pvc
    storageClassName: openebs-rawfile-localpv
    accessModes:
    - ReadWriteOnce
    size: 500Mi
    finalizers:
    - kubernetes.io/pvc-protection
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: true
      org_name: "Main Org."
      org_role: Admin
      hide_version: true
    paths:
      data: /var/lib/grafana/data
  additionalDataSources:
    - name: Loki
      access: proxy
      type: loki
      url: http://loki-loki-distributed-gateway
      version: 1
  sidecar:
    logLevel: DEBUG
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      searchNamespace: ALL
    notifiers:
      enabled: true
      searchNamespace: ALL
