name: Make Release Notes

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
        description: "What tag to release"

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ inputs.tag }}"

      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Yarn install
        run: |
          yarn install

      - name: Get namespace
        id: namespace
        run: |
          name="$(echo ${{ inputs.tag }} | sed -E 's/(.*)-v[[:digit:]]+.[[:digit:]]+.[[:digit:]]+/\1/g')"
          echo "name=$name" >> $GITHUB_OUTPUT

      - name: Generate release notes
        env:
          NAMESPACE: ${{ steps.namespace.outputs.name }}
        run: |
          export GIT_CLIFF__GIT__TAG_PATTERN="$NAMESPACE-v*"
          export GIT_CLIFF__GIT__IGNORE_TAGS="$NAMESPACE-v[0-9]+.[0-9]+.[0-9]+-.*"

          yarn git-cliff -c ".cliff.toml" --include-path "$NAMESPACE/**" -o "RELEASE-NOTES.md" -s all -t "${{ inputs.tag }}"

      - uses: actions/upload-artifact@v3
        with:
          name: "${{ inputs.tag }}.release-notes"
          path: RELEASE-NOTES.md
